# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      puppeteer_version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'puppeteer version'
        # Default value if no value is explicitly provided
        default: '8.0.0'
        # Input has to be provided for the workflow to run
        required: true
      node_version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'node version'
        # Default value if no value is explicitly provided
        default: '15'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  handtest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ github.event.inputs.node_version }}

      - name: 'Fix for: error fsevents@2.1.2: The platform "linux" is incompatible with this module.'
        run: npx json -I -f package.json -e 'this.resolutions={}'

      - name: yarn install
        uses: bahmutov/npm-install@v1

      - name: yarn bootstrap
        run: yarn bootstrap

      - name: install puppeteer ${{ github.event.inputs.puppeteer_version }}
        run: yarn lerna add --dev puppeteer@${{ github.event.inputs.puppeteer_version }}

      - name: lerna link
        run: yarn lerna link

      - name: lerna build
        run: yarn lerna run build --concurrency 1

      - name: debug
        run: |
          yarn list --pattern "puppeteer|puppeteer-extra"
          file node_modules/puppeteer-extra/dist/index.cjs.js
      - uses: microsoft/playwright-github-action@v1

      - name: test
        uses: GabrielBB/xvfb-action@v1
        env:
          DISPLAY: ":99.0"
        with:
          run: yarn test-ci
